first pass at implementing curved links

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2004,6 +2004,269 @@ else
 TCL_CFLAGS="-I$with_tcl"
 TCL_LIBS="-ltcl -ltclstub"
 fi
+$ECHO_N 'checking for Agar-Math...'
+$ECHO_N '# checking for Agar-Math...' >>config.log
+# BEGIN agar-math(1.6.0 ${prefix_agar})
+AGAR_MATH_VERSION=
+if [ "${prefix_agar}" != "" ]; then
+if [ -e "${prefix_agar}/bin/agar-math-config" ]; then
+AGAR_MATH_VERSION=`${prefix_agar}/bin/agar-math-config --version`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${prefix_agar}/bin/agar-math-config"
+fi
+else
+bb_save_IFS=$IFS
+IFS=$PATH_SEPARATOR
+for path in $PATH; do
+if [ -e "${path}/agar-math-config" ]; then
+AGAR_MATH_VERSION=`${path}/agar-math-config --version`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config"
+break
+elif [ -e "${path}/agar-math-config.exe" ]; then
+AGAR_MATH_VERSION=`${path}/agar-math-config.exe --version`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config.exe"
+break
+fi
+done
+IFS=$bb_save_IFS
+fi
+if [ "${AGAR_MATH_VERSION}" != "" ]; then
+if [ "${prefix_agar}" != "" ]; then
+echo "yes ($AGAR_MATH_VERSION in ${prefix_agar})"
+echo "# yes ($AGAR_MATH_VERSION in ${prefix_agar})" >>config.log
+else
+echo "yes ($AGAR_MATH_VERSION)"
+echo "# yes ($AGAR_MATH_VERSION)" >>config.log
+fi
+MK_VERSION_MAJOR=`echo "$AGAR_MATH_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\1/'`;
+MK_VERSION_MINOR=`echo "$AGAR_MATH_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\2/'`;
+MK_VERSION_MICRO=`echo "$AGAR_MATH_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\3/'`;
+MK_VERSION_OK=no
+if [ $MK_VERSION_MAJOR -gt 1 ]; then
+MK_VERSION_OK=yes
+elif [ $MK_VERSION_MAJOR -eq 1 ]; then
+if [ "$MK_VERSION_MINOR" = '' ]; then
+MK_VERSION_OK=yes
+else
+if [ $MK_VERSION_MINOR -gt 6 ]; then
+MK_VERSION_OK=yes
+elif [ $MK_VERSION_MINOR -eq 6 ]; then
+if [ "$MK_VERSION_MICRO" = '' ]; then
+MK_VERSION_OK=yes
+else
+if [ $MK_VERSION_MICRO -ge 0 ]; then
+MK_VERSION_OK=yes
+fi
+fi
+fi
+fi
+fi
+if [ "${MK_VERSION_OK}" = "no" ]; then
+echo '*'
+echo '# *' >>config.log
+echo "* Minimum required version is 1.6.0 (found $AGAR_MATH_VERSION)"
+echo "# * Minimum required version is 1.6.0 (found $AGAR_MATH_VERSION)" >>config.log
+echo '*'
+echo '# *' >>config.log
+fi
+else
+if [ "${prefix_agar}" != "" ]; then
+echo "no (not in ${prefix_agar})"
+echo "# no (not in ${prefix_agar})" >>config.log
+else
+echo 'no'
+echo '# no' >>config.log
+fi
+MK_VERSION_OK="no"
+fi
+if [ "${MK_VERSION_OK}" = "yes" ]; then
+$ECHO_N 'checking whether Agar-Math works...'
+$ECHO_N '# checking whether Agar-Math works...' >>config.log
+AGAR_CFLAGS=
+if [ "${prefix_agar}" != "" ]; then
+if [ -e "${prefix_agar}/bin/agar-config" ]; then
+AGAR_CFLAGS=`${prefix_agar}/bin/agar-config --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${prefix_agar}/bin/agar-config"
+fi
+else
+bb_save_IFS=$IFS
+IFS=$PATH_SEPARATOR
+for path in $PATH; do
+if [ -e "${path}/agar-config" ]; then
+AGAR_CFLAGS=`${path}/agar-config --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-config"
+break
+elif [ -e "${path}/agar-config.exe" ]; then
+AGAR_CFLAGS=`${path}/agar-config.exe --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-config.exe"
+break
+fi
+done
+IFS=$bb_save_IFS
+fi
+AGAR_LIBS=
+if [ "${prefix_agar}" != "" ]; then
+if [ -e "${prefix_agar}/bin/agar-config" ]; then
+AGAR_LIBS=`${prefix_agar}/bin/agar-config --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${prefix_agar}/bin/agar-config"
+fi
+else
+bb_save_IFS=$IFS
+IFS=$PATH_SEPARATOR
+for path in $PATH; do
+if [ -e "${path}/agar-config" ]; then
+AGAR_LIBS=`${path}/agar-config --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-config"
+break
+elif [ -e "${path}/agar-config.exe" ]; then
+AGAR_LIBS=`${path}/agar-config.exe --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-config.exe"
+break
+fi
+done
+IFS=$bb_save_IFS
+fi
+AGAR_MATH_CFLAGS=
+if [ "${prefix_agar}" != "" ]; then
+if [ -e "${prefix_agar}/bin/agar-math-config" ]; then
+AGAR_MATH_CFLAGS=`${prefix_agar}/bin/agar-math-config --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${prefix_agar}/bin/agar-math-config"
+fi
+else
+bb_save_IFS=$IFS
+IFS=$PATH_SEPARATOR
+for path in $PATH; do
+if [ -e "${path}/agar-math-config" ]; then
+AGAR_MATH_CFLAGS=`${path}/agar-math-config --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config"
+break
+elif [ -e "${path}/agar-math-config.exe" ]; then
+AGAR_MATH_CFLAGS=`${path}/agar-math-config.exe --cflags`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config.exe"
+break
+fi
+done
+IFS=$bb_save_IFS
+fi
+AGAR_MATH_LIBS=
+if [ "${prefix_agar}" != "" ]; then
+if [ -e "${prefix_agar}/bin/agar-math-config" ]; then
+AGAR_MATH_LIBS=`${prefix_agar}/bin/agar-math-config --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${prefix_agar}/bin/agar-math-config"
+fi
+else
+bb_save_IFS=$IFS
+IFS=$PATH_SEPARATOR
+for path in $PATH; do
+if [ -e "${path}/agar-math-config" ]; then
+AGAR_MATH_LIBS=`${path}/agar-math-config --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config"
+break
+elif [ -e "${path}/agar-math-config.exe" ]; then
+AGAR_MATH_LIBS=`${path}/agar-math-config.exe --libs`
+MK_EXEC_FOUND=Yes
+MK_EXEC_PATH="${path}/agar-math-config.exe"
+break
+fi
+done
+IFS=$bb_save_IFS
+fi
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+#include <agar/core.h>
+#include <agar/math.h>
+
+int main(int argc, char *argv[]) {
+	M_Matrix *A = M_New(2,2);
+	AG_InitCore("test", 0);
+	M_InitSubsystem();
+	M_SetIdentity(A);
+	AG_Destroy();
+	return (0);
+}
+EOT
+echo >>config.log
+echo '# C: HAVE_AGAR_MATH' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_MATH_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest$$ conftest$$.c ${AGAR_MATH_LIBS} ${AGAR_LIBS} 2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_MATH_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest$$ conftest$$.c ${AGAR_MATH_LIBS} ${AGAR_LIBS} 2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_AGAR_MATH=yes
+echo "hdefs[\"HAVE_AGAR_MATH\"] = \"$HAVE_AGAR_MATH\"" >>configure.lua
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_AGAR_MATH=no
+echo 'hdefs["HAVE_AGAR_MATH"] = nil' >>configure.lua
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
+if [ "${HAVE_AGAR_MATH}" = "yes" ]; then
+echo "hdefs[\"AGAR_MATH_CFLAGS\"] = \"$AGAR_MATH_CFLAGS\"" >>configure.lua
+echo "hdefs[\"AGAR_MATH_LIBS\"] = \"$AGAR_MATH_LIBS\"" >>configure.lua
+else
+echo 'hdefs["AGAR_MATH_CFLAGS"] = nil' >>configure.lua
+AGAR_MATH_CFLAGS=""
+echo 'hdefs["AGAR_MATH_LIBS"] = nil' >>configure.lua
+AGAR_MATH_LIBS=""
+fi
+else
+HAVE_AGAR_MATH="no"
+AGAR_MATH_CFLAGS=""
+AGAR_MATH_LIBS=""
+echo 'hdefs["HAVE_AGAR_MATH"] = nil' >>configure.lua
+echo 'hdefs["AGAR_MATH_CFLAGS"] = nil' >>configure.lua
+echo 'hdefs["AGAR_MATH_LIBS"] = nil' >>configure.lua
+fi
+# END agar-math
+if [ "${HAVE_AGAR_MATH}" != "yes" ]; then
+echo '* '
+echo '# * ' >>config.log
+echo "* $PACKAGE requires Agar-Math (version 1.6.0 or newer)."
+echo "# * $PACKAGE requires Agar-Math (version 1.6.0 or newer)." >>config.log
+echo '* WWW: http://libagar.org'
+echo '# * WWW: http://libagar.org' >>config.log
+echo '* '
+echo '# * ' >>config.log
+echo "Required dependency agar-math not found"
+exit 1
+fi
+if [ "${MK_VERSION_OK}" != "yes" ]; then
+echo '* '
+echo '# * ' >>config.log
+echo '* This software requires agar-math version >= 1.6.0,'
+echo '# * This software requires agar-math version >= 1.6.0,' >>config.log
+echo '* please update that package and try again.'
+echo '# * please update that package and try again.' >>config.log
+echo '* WWW: http://libagar.org'
+echo '# * WWW: http://libagar.org' >>config.log
+echo '* '
+echo '# * ' >>config.log
+echo "Required dependency agar-math version mismatch"
+exit 1
+fi
 if [ "${enable_debugger}" = "yes" ] 
  then
 CFLAGS="$CFLAGS -DENABLE_DEBUGGER"
@@ -2024,6 +2287,10 @@ echo "AGAR_CFLAGS=$AGAR_CFLAGS" >>Makefile.config
 echo "mdefs[\"AGAR_CFLAGS\"] = \"$AGAR_CFLAGS\"" >>configure.lua
 echo "AGAR_LIBS=$AGAR_LIBS" >>Makefile.config
 echo "mdefs[\"AGAR_LIBS\"] = \"$AGAR_LIBS\"" >>configure.lua
+echo "AGAR_MATH_CFLAGS=$AGAR_MATH_CFLAGS" >>Makefile.config
+echo "mdefs[\"AGAR_MATH_CFLAGS\"] = \"$AGAR_MATH_CFLAGS\"" >>configure.lua
+echo "AGAR_MATH_LIBS=$AGAR_MATH_LIBS" >>Makefile.config
+echo "mdefs[\"AGAR_MATH_LIBS\"] = \"$AGAR_MATH_LIBS\"" >>configure.lua
 echo "BINDIR=$BINDIR" >>Makefile.config
 echo "mdefs[\"BINDIR\"] = \"$BINDIR\"" >>configure.lua
 echo "CC=$CC" >>Makefile.config
@@ -2040,6 +2307,8 @@ echo "EXECSUFFIX=$EXECSUFFIX" >>Makefile.config
 echo "mdefs[\"EXECSUFFIX\"] = \"$EXECSUFFIX\"" >>configure.lua
 echo "HAVE_AGAR=$HAVE_AGAR" >>Makefile.config
 echo "mdefs[\"HAVE_AGAR\"] = \"$HAVE_AGAR\"" >>configure.lua
+echo "HAVE_AGAR_MATH=$HAVE_AGAR_MATH" >>Makefile.config
+echo "mdefs[\"HAVE_AGAR_MATH\"] = \"$HAVE_AGAR_MATH\"" >>configure.lua
 echo "HAVE_CC=$HAVE_CC" >>Makefile.config
 echo "mdefs[\"HAVE_CC\"] = \"$HAVE_CC\"" >>configure.lua
 echo "HAVE_CC65=$HAVE_CC65" >>Makefile.config
